version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # Painel web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - spark-net
  postgres:
    image: postgres:15
    container_name: postgres_streaming
    environment:
      POSTGRES_USER: spark
      POSTGRES_PASSWORD: spark123
      POSTGRES_DB: streaming
    ports:
      - "5432:5432"
    networks:
      - spark-net
  
networks:
  spark-net:
    name: gab_spark-net
    driver: bridge
