version: '3'

services:
  spark-master:
    image: bitnami/spark:3.1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "8080:8080"  # Spark UI
    networks:
      - spark-net
    volumes:
      - spark-master-data:/opt/bitnami/spark/data

  spark-worker-1:
    image: bitnami/spark:3.1
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-net
    volumes:
      - spark-worker-1-data:/opt/bitnami/spark/data

  spark-worker-2:
    image: bitnami/spark:3.1
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-net
    volumes:
      - spark-worker-2-data:/opt/bitnami/spark/data

networks:
  spark-net:
    driver: bridge

volumes:
  spark-master-data:
    driver: local
  spark-worker-1-data:
    driver: local
  spark-worker-2-data:
    driver: local
